services:
  app_amarhu:
    build:
      context: ./amarhu-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_PROJECT_ID: ${GOOGLE_PROJECT_ID}
    deploy:
      resources:
        limits:
          memory: 512M    # Limita la memoria del contenedor a 512 MB
          cpus: "0.5"     # Limita el uso de CPU a medio núcleo
    restart: always
    depends_on:
      db_amarhu:
        condition: service_healthy

  db_amarhu:
    image: mysql:9.1.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password123#
      MYSQL_DATABASE: amarhu_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
    command: --max_connections=20 --table_open_cache=32 --key_buffer_size=8M --max_heap_table_size=8M --innodb_buffer_pool_size=128M --innodb_log_file_size=16M --innodb_log_buffer_size=8M --innodb_flush_log_at_trx_commit=1
    restart: always
