services:
  app_amarhu:
    build:
      context: ./amarhu-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_PROJECT_ID: ${GOOGLE_PROJECT_ID}
      MYSQL_URL: ${MYSQL_URL}
      MYSQLUSER: ${MYSQLUSER}
      MYSQLPASSWORD: ${MYSQLPASSWORD}
      
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
    restart: always
