services:
  app_amarhu:
    build:
      context: ./amarhu-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_PROJECT_ID: ${GOOGLE_PROJECT_ID}
    restart: always
    depends_on:
      db_amarhu:
        condition: service_healthy
  db_amarhu:
    image: mysql:9.1.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password123#
      MYSQL_DATABASE: amarhu_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    restart: always
